<?php

declare(strict_types=1);

/** @var Magewire $magewireScripts */
/** @var Escaper $escaper */
/** @var Template $block */

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Magewirephp\Magewire\ViewModel\Magewire;

$magewireScripts = $block->getViewModel();
?>

<script>
    window.magewire = new Livewire();
    window.Livewire = window.magewire
    window.Magewire = window.magewire
    window.livewire_app_url = '<?= $escaper->escapeUrl($magewireScripts->getApplicationUrl()) ?>'
    window.livewire_token = window.hyva.getFormKey()
</script>
