<?php
/**
 * @author    JaJuMa GmbH <info@jajuma.de>
 * @copyright Copyright (c) 2023 JaJuMa GmbH <https://www.jajuma.de>. All rights reserved.
 * @license   http://opensource.org/licenses/mit-license.php MIT License
 */

use Jajuma\PowerToys\Block\PowerToys\QuickAction;
use Magento\Framework\Escaper;

/** @var QuickAction $block */
/** @var Escaper $escaper */

?>
<div class="action-item-content action-item-content-<?= $block->getData('block_id') ?>">
    <b><?= $block->getName() ?></b>
    <p><?= 'Example Action modal' ?></p>
</div>
