<style>
    :root {
        --jajuma-develop-black-module: #3c3c3c;
        --jajuma-develop-module: #efb600;
        --jajuma-develop-light-module: #ffe9a3;
        --jajuma-develop-lighter-module: #fff5d5;
    }

    #jajuma-powertoys-floating-panel {
        z-index: 999;
        position: fixed;
        transform: translate(-50%, -50%);
        top: 40%;
        left: 30px;
        width: 50px;
        height: 50px;
        border-radius: 50%;
        cursor: pointer;
        color: var(--jajuma-develop-black-module);
        font-size: 14px;
        font-family: Arial;
        line-height: normal;
    }

    #jajuma-powertoys-floating-panel:not(.mousehold) {
        transition: left .1s ease;
    }

    #jajuma-powertoys-floating-panel.mousehold .powertoys-actions-list,
    #jajuma-powertoys-floating-panel.mousehold .powertoys-dashboard-widgets,
    #jajuma-powertoys-floating-panel.mousehold .powertoys-bookmark-bar {
        cursor: grabbing;
    }

    #jajuma-powertoys-floating-panel,
    #jajuma-powertoys-floating-panel ~ .powerToysModalWrapper {
        color: #fff;
    }

    #jajuma-powertoys-floating-panel.jajumaLightMode,
    #jajuma-powertoys-floating-panel.jajumaLightMode ~ .powerToysModalWrapper {
        color: var(--jajuma-develop-black-module);
    }

    #jajuma-powertoys-floating-panel .powertoys-dashboard-widgets,
    #jajuma-powertoys-floating-panel .powertoys-bookmark-bar {
        color: var(--jajuma-develop-black-module);
    }

    #jajuma-powertoys-floating-panel.onRight {
        transform: translate(calc(-50% - 10px), -50%);
    }

    .powertoys-actions ul,
    .powertoys-dashboard-widgets,
    .powertoys-bookmark-bar {
        overflow-x: auto;
        -ms-overflow-style: none;
        scrollbar-width: none;
        /*scroll-behavior: smooth;*/
        background: rgb(239 239 239 / 20%);
        padding: 10px;
        padding-left: 0;
        border-left: 10px solid rgba(0, 0, 0, 0);
        gap: 8px;
        border-radius: 10px;
        box-shadow: 1px 1px 5px 0px rgba(0, 0, 0, 0.05);
        -ms-overflow-style: none;
        scrollbar-width: none;
    }

    .powertoys-actions-list.smoothy,
    .powertoys-dashboard-widgets.smoothy,
    .powertoys-bookmark-bar.smoothy {
        scroll-behavior: smooth;
    }

    .powertoys-actions ul::-webkit-scrollbar,
    .powertoys-dashboard-widgets::-webkit-scrollbar,
    .powertoys-bookmark-bar::-webkit-scrollbar {
        display: none;
    }

    .jajumaLightMode .powertoys-actions ul,
    .jajumaLightMode .powertoys-dashboard-widgets,
    .jajumaLightMode .powertoys-bookmark-bar {
        background: rgba(255, 255, 255, .67);
        box-shadow: 1px 1px 5px 0px rgb(0 0 0 / 10%);
    }

    .powertoys-actions ul li span,
    .powertoys-bookmark-bar .bookmark-item {
        display: inline-flex;
        align-items: center;
        white-space: nowrap;
        border-radius: 6px;
        gap: 4px;
        background: var(--jajuma-develop-light-module, #FFE9A3);
        box-shadow: 1px 1px 5px 0px rgba(0, 0, 0, 0.05);
        font-size: 14px;
        padding: 8px 10px;
        transition: .3s ease color;
        text-decoration: none;
        cursor: pointer;
        color: inherit;
        text-decoration: none;
        user-select: none;
        -webkit-user-select: none;
        -moz-user-select: none;
    }

    .powertoys-actions ul li span {
        background-color: transparent;
        border: 0.5px solid #fff;
        width: max-content;
    }

    .powertoys-actions ul li span img {
        border-radius: 50%;
        padding: 0;
        background: #fff;
        border: 2px solid #FFF;
        height: 20px;
        width: 20px;
        object-fit: contain;
    }

    .jajumaLightMode .powertoys-actions ul li span img {
        background: rgba(0, 0, 0, 0);
        border: 2px solid rgba(0, 0, 0, 0);
        object-fit: contain;
    }

    .jajumaLightMode .powertoys-actions ul li span {
        color: var(--jajuma-develop-black-module);
        border-color: var(--jajuma-develop-black-module);
    }

    .jajumaLightMode .powertoys-actions ul li span:hover {
        border-color: var(--jajuma-develop-black-module);
    }

    #jajuma-powertoys-floating-panel .jajuma-powertoys-floating-btn {
        position: absolute;
        top: 0;
        left: 0;
        display: flex;
        justify-content: center;
        align-items: center;
        width: 100%;
        height: 100%;
        border-radius: 50%;
        background: var(--jajuma-develop-gradient, linear-gradient(-30deg, rgba(255, 233, 163, 0.90) 0%, rgba(255, 245, 213, 0.90) 100%));
        color: white;
        z-index: 999;
        box-shadow: 2px 2px 20px rgba(0, 0, 0, 0.15);
        padding: 5px;
    }

    #jajuma-powertoys-floating-panel .jajuma-powertoys-floating-btn img {
        transform: scale(0.8);
        transition: transform .3s ease;
    }

    #jajuma-powertoys-floating-panel .jajuma-powertoys-floating-btn:hover img {
        transform: scale(1);
    }

    /* PowerToys Panel */

    .powertoys-panel-header {
        padding: 0 0 15px;
        display: flex;
        justify-content: space-between;
    }

    .powertoys-panel-title {
        display: flex;
        align-items: end;
        font-weight: 700;
    }

    .powertoys-panel-title img {
        width: 32px;
    }

    .powertoys-panel-title span {
        margin-left: 10px;
        margin-bottom: 3px;
        font-size: 16px;
    }

    .powertoys-panel-footer {
        padding: 10px 0px 0px;
        display: flex;
        justify-content: space-between;
        margin-bottom: -10px;
    }

    .powertoys-footer-left a {
        color: #fff;
    }

    .powertoys-footer-right {
        display: flex;
    }

    .powertoys-footer-right svg {
        width: 60px;
        height: auto;
        color: #fff;
    }

    .jajumaLightMode .powertoys-footer-left a,
    .jajumaLightMode .powertoys-footer-right svg {
        color: #3c3c3c;
    }

    .jajumaLightMode .powertoys-panel-title span {
        color: var(--jajuma-develop-black-module);
    }

    .jajumaLightMode .powertoys-close-panel-btn svg {
        color: var(--jajuma-develop-black-module);
    }

    .powertoys-header-right {
        display: flex;
    }

    .powertoys-header-right svg {
        width: 24px;
        cursor: pointer;
    }

    .powertoys-darklight-switcher {
        position: relative;
        margin-right: 10px;
        width: 20px;
    }

    .powertoys-darklight-switcher svg {
        position: absolute;
        top: 0;
        left: 0;
        width: 20px;
        margin-top: 2px;
        transform-origin: center;
        transition-duration: .3s;
        transition-timing-function: cubic-bezier(.4, 0, .2, 1);
        transition-property: transform, opacity;
    }

    .powertoys-darklight-switcher .powertoys-sun,
    .jajumaLightMode .powertoys-darklight-switcher .powertoys-moon {
        opacity: 0;
        transform: rotate(45deg);
    }

    .jajumaLightMode .powertoys-darklight-switcher .powertoys-sun {
        opacity: 1;
        transform: rotate(0deg);
    }

    #jajuma-powertoys-floating-panel .power-toys-container {
        visibility: hidden;
        display: flex;
        flex-direction: column;
        justify-content: space-between;
        position: absolute;
        min-width: 500px;
        max-width: 80vw;
        min-height: 300px;
        padding: 15px;
        border-radius: 24px;
        backdrop-filter: blur(4px);
        background: #20202078 radial-gradient(#1a1f35a3 25%, #202020d4 100%) no-repeat fixed;
        box-shadow: 2px 2px 10px 0px rgba(0, 0, 0, 0.10);
        width: fit-content;
        pointer-events: none;
        opacity: 0;
        transition: opacity, transform .3s ease;
        cursor: default;
        z-index: 1000;
    }

    #jajuma-powertoys-floating-panel.jajumaLightMode .power-toys-container,
    #jajuma-powertoys-floating-panel.jajumaLightMode ~ .powerToysModalWrapper .powertoys-modal {
        background: #f3f3f38c radial-gradient(#eff4f9ed 75%, #f3f3f380 100%) no-repeat fixed;
        box-shadow: 0 0 6px #00000040;
    }

    #jajuma-powertoys-floating-panel.powerToys-active .power-toys-container {
        pointer-events: all;
        opacity: 1;
        visibility: visible;
    }

    #jajuma-powertoys-floating-panel.onLeft .power-toys-container {
        transform-origin: left top;
        transform: scale(.9);
    }

    #jajuma-powertoys-floating-panel.powerToys-active.onLeft .power-toys-container {
        left: calc(100% + 10px);
        transform: scale(1);
    }

    #jajuma-powertoys-floating-panel.powerToys-active.onLeft.onBottom .power-toys-container {
        /*transform: scale(1) translateY(-100%);*/
    }

    #jajuma-powertoys-floating-panel.onRight .power-toys-container {
        transform-origin: right top;
        transform: scale(.9) translateX(-100%);
    }

    #jajuma-powertoys-floating-panel.powerToys-active.onRight .power-toys-container {
        left: -10px;
        transform: scale(1) translateX(-100%);
    }

    #jajuma-powertoys-floating-panel.powerToys-active.onRight.onBottom .power-toys-container {
        /*transform: scale(1) translate(-100%, -100%);*/
    }

    #jajuma-powertoys-floating-panel.powerToys-active.onRight.onBottom.lessHeight .power-toys-container {
        /*transform: scale(1) translate(-100%, -100%);*/
    }

    .powertoys-actions ul {
        display: flex;
        margin-top: 2px;
        margin-bottom: 10px;
        list-style: none;
        overflow-x: auto;
    }

    .powertoys-action-item {
        position: relative;
        min-height: 24px;
    }

    .powertoys-dashboard-widgets {
        position: relative;
        display: flex;
        gap: 15px;
        max-height: 200px;
    }

    .pot-navigation {
        position: fixed;
        background: #000000b3;
        height: 20px;
        min-width: 20px;
        transform: translate(-7px, 50%);
        display: inline-flex;
        align-items: center;
        justify-content: center;
        z-index: 10;
        opacity: 0;
        transition: .5s ease opacity;
        border-radius: 100%;
        cursor: pointer;
    }
    .powertoys-dashboard-widgets:hover .pot-navigation,
    .powertoys-actions-list:hover .pot-navigation,
    .powertoys-bookmark-bar:hover .pot-navigation
    {
        opacity: .8;
    }

    .power-toys-container .hide-arrow-left .pot-previous,
    .power-toys-container .hide-arrow-right .pot-next {
        display: none !important;
    }

    .powertoys-dashboard-widgets .pot-navigation {
        height: 80px;
        transform: translate(-10px, 50%);
    }

    .pot-navigation:not(.disable):hover {
        opacity: 1;
    }

    .pot-navigation svg {
        color: #fff;
        width: 16px;
    }

    .pot-next {
        right: 28px;
        transform: translate(10px, 50%);
    }

    .powertoys-dashboard-widgets .pot-previous {
        border-top-right-radius: 6px;
        border-bottom-right-radius: 6px;
        border-top-left-radius: 0;
        border-bottom-left-radius: 0;
    }

    .powertoys-dashboard-widgets .pot-next {
        border-top-left-radius: 6px;
        border-bottom-left-radius: 6px;
        border-top-right-radius: 0;
        border-bottom-right-radius: 0;
        right: 24px;
        transform: translate(10px, 50%);
    }

    .powertoys-dashboard-widgets .widget-item {
        border-radius: 16px;
        box-shadow: 1px 1px 5px 0px rgba(0, 0, 0, 0.05);
        background: rgba(255, 255, 255, 0.9);
        padding: 10px;
        min-height: 150px;
        display: inline-block;
        min-width: 240px;
        position: relative;
    }

    .jajumaLightMode .powertoys-dashboard-widgets .widget-item {
        background: rgb(232 232 232);
    }

    .openSubPanel .power-toys-container:after {
        content: "";
        width: 100%;
        height: 100%;
        top: 0;
        left: 0;
        position: absolute;
        border-radius: 24px;
        opacity: 1;
        backdrop-filter: blur(1.8px);
        transition: visibility 0s linear 0.1s, opacity 0.3s ease;
        z-index: 1;
    }

    .powertoys-widget-title {
        margin-bottom: 10px;
        font-size: 12px;
        padding: 0 6px;
        color: #fff;
        border-radius: 16px;
        display: inline-block;
        width: fit-content;
        height: 18px;
        line-height: 18px;
        background: #3c3c3c;
    }

    .powertoys-widget-title.title-transparent {
        background: rgba(0, 0, 0, 0);
        border: 1px solid #fff;
    }

    @media (min-width: 1024px) {
        #jajuma-powertoys-floating-panel .power-toys-container {
            min-width: 1024px !important;
        }
    }

    /* PowerToys Modal */

    .powerToysModalWrapper {
        z-index: 1000;
        position: fixed;
        width: 100%;
        height: 100%;
        pointer-events: none;
        visibility: hidden;
    }

    .powerToysModalWrapper.open {
        visibility: visible;
    }

    .powerToysModalWrapper .powertoys-modal {
        padding: 30px;
        min-width: 300px;
        min-height: 200px;
        margin: 0;
        padding: 0;
        opacity: 0;
        visibility: hidden;
        padding: 15px;
        border-radius: 24px;
        backdrop-filter: blur(4px);
        background: #2020209c radial-gradient(#1a1f35 25%, #202020db 100%) no-repeat fixed;
        box-shadow: 2px 2px 10px 0px rgb(255 255 255 / 10%);
        width: fit-content;
        opacity: 0;
        transform: scale(.9);
        transition: opacity, transform .3s ease;
    }

    #jajuma-powertoys-floating-panel.jajumaLightMode .powerToysModalWrapper .powertoys-modal {
        background: #f3f3f38c radial-gradient(#eff4f9ed 75%, #f3f3f380 100%) no-repeat fixed;
        box-shadow: 0 0 6px #00000040;
    }

    .jajumaLightMode ~ .powerToysModalWrapper .powertoys-modal {
        box-shadow: 2px 2px 10px 0px rgba(0, 0, 0, 0.10);
    }

    .powerToysModalWrapper .powertoys-modal.open {
        position: absolute;
        opacity: 1;
        transform: scale(1);
        visibility: visible;
        pointer-events: all;
    }

    #jajuma-powertoys-floating-panel.onRight~.powerToysModalWrapper .powertoys-modal {
        transform: scale(.9) translateX(-70%);
    }


    #jajuma-powertoys-floating-panel.onRight~.powerToysModalWrapper .powertoys-modal.open {
        transform: scale(1) translateX(-70%);
    }

    .powerToysModalWrapper svg {
        width: 24px;
        cursor: pointer;
    }

    /* Loading Dots */

    .powertoys-loading-wrapper {
        visibility: hidden;
        margin: 0 10px 10px 0;
        padding: 20px 20px 20px;
        text-align: center;
        z-index: 100;
        position: absolute;
        left: 0;
        top: 0;
        width: 100%;
        height: 100%;
        border-radius: 24px;
        display: flex;
        align-items: center;
        justify-content: center;
        backdrop-filter: blur(1.8px);
        pointer-events: none;
    }

    .powertoysloading .powertoys-loading-wrapper {
        visibility: visible;
    }

    .powertoys-dot {
        display: inline-block;
        width: 15px;
        height: 15px;
        border-radius: 15px;
        background-color: var(--jajuma-develop-module);
    }

    .powertoys-dots .powertoys-dot:nth-last-child(1) {
        animation: loadingDots 0.6s 0.1s linear infinite;
    }

    .powertoys-dots .powertoys-dot:nth-last-child(2) {
        animation: loadingDots 0.6s 0.2s linear infinite;
    }

    .powertoys-dots .powertoys-dot:nth-last-child(3) {
        animation: loadingDots 0.6s 0.3s linear infinite;
    }

    @keyframes loadingDots {
        0 {
            transform: translate(0, 0);
        }

        50% {
            transform: translate(0, 15px);
        }

        100% {
            transform: translate(0, 0);
        }
    }

    /* Components */

    .powerToysModalWrapper {
        font-size: 14px;
    }

    .powerToysModalWrapper .powertoys-panel-title span {
        margin-left: 0;
    }

    .powerToysModalWrapper input,
    .powerToysModalWrapper textarea,
    .powerToysModalWrapper select {
        border: 1px solid #fff;
        border-radius: 4px;
        background-color: #191919;
        padding: 2px 8px;
        min-height: 32px;
    }

    .powerToysModalWrapper input:focus,
    .powerToysModalWrapper textarea:focus,
    .powerToysModalWrapper select:focus {
        border-color: var(--jajuma-develop-module) !important;
        box-shadow: none !important;
    }

    .jajumaLightMode .powerToysModalWrapper input,
    .jajumaLightMode ~ .powerToysModalWrapper input,
    .jajumaLightMode .powerToysModalWrapper textarea,
    .jajumaLightMode ~ .powerToysModalWrapper textarea,
    .jajumaLightMode .powerToysModalWrapper select,
    .jajumaLightMode ~ .powerToysModalWrapper select {
        border: 1px solid var(--jajuma-develop-black-module);
        background-color: #ffffffc7;
    }

    .powerToysModalWrapper select {
        padding-right: 32px;
    }

    .powerToysModalWrapper button,
    .powerToysModalWrapper .btn {
        min-height: 32px;
        padding: 2px 12px;
        display: inline-block;
        font-weight: 700;
        color: var(--jajuma-develop-black-module);
        border: 0.5px solid var(--jajuma-develop-black-module, #3C3C3C);
        border-radius: 4px;
        background: var(--jajuma-develop-light-module, #FFE9A3);
        color: var(--jajuma-develop-black-module);
        transition: .3s ease color;
    }

    .powerToysModalWrapper .btn:hover {
        color: var(--jajuma-develop-black-module);
        background: var(--jajuma-develop-module);
        cursor: pointer;
    }

    .powerToysModalWrapper button:hover {
        color: var(--jajuma-develop-black-module);
        background: var(--jajuma-develop-module);
    }

    #jajuma-powertoys-floating-panel #powertoys-bookmark-modal {
        top: 50px;
        left: 50px;
    }

    #jajuma-powertoys-floating-panel.onRight #powertoys-bookmark-modal {
        left: -50px;
    }

    .bookmarkModal .bookmark-icon-item {
        width: 24px;
        height: 24px;
        display: inline-block;
        -webkit-touch-callout: none;
        -webkit-user-select: none;
        -khtml-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
    }

    .bookmarkModal .bookmark-icon-item.selected {
        position: relative;
        border-radius: 50%;
        background-color: var(--jajuma-develop-module);
    }

    .bookmarkModal .bookmark-icon-item.selected::after {
        position: absolute;
        content: "";
        height: 32px;
        width: 32px;
        background: var(--jajuma-develop-module);
        border-radius: 50%;
        top: -4px;
        left: -4px;
        z-index: -1;
    }

    .powertoys-bookmark-bar {
        display: flex;
        gap: 8px;
        margin-top: 15px;
    }

    .powertoys-actions ul li span:hover,
    .powertoys-bookmark-bar .bookmark-item:hover {
        background: var(--jajuma-develop-module);
        color: var(--jajuma-develop-black-module);
        border-color: var(--jajuma-develop-module);
    }

    /* Bookmark settings */

    .powertoys-bookmark-settings .field {
        display: flex;
        align-items: center;
        margin-top: 10px;
    }

    .powertoys-bookmark-settings .field.status {
        margin-top: 0;
    }

    .powertoys-bookmark-settings .field label {
        width: 20%;
        float: left;
        text-align: left;
    }

    .powertoys-bookmark-settings .field .control {
        width: 80%;
        padding: 2px 3px;
    }

    .powertoys-bookmark-settings .field input {
        width: 100%;
    }

    .powertoys-bookmark-settings .field input#position {
        width: 60px;
    }

    .powertoys-bookmark-settings .bookmark-icon-list .control {
        height: 80px;
        overflow-y: auto;
        padding: 5px;
    }

    .bookmarkModal .powertoys-actions {
        display: flex;
        justify-content: end;
        margin-top: 15px;
    }

    .bookmarkModal .powertoys-actions .action-btn-secondary,
    .bookmarkModal .powertoys-actions .action-btn-primary {
        margin-left: 10px;
        padding: 10px 20px;
        line-height: 16px;
        border: 1px solid var(--jajuma-develop-module);
        font-size: 16px;
        font-weight: 400;
    }

    .bookmarkModal .powertoys-actions .action-btn-secondary {
        color: var(--jajuma-develop-module);
        background-color: rgba(0, 0, 0, 0);
    }

    .bookmarkModal .powertoys-actions .action-btn-secondary:hover {
        background-color: var(--jajuma-develop-lighter-module);
    }

    @media (max-width: 1024px) {
        #jajuma-powertoys-floating-panel #powertoys-bookmark-modal {
            top: 0;
            left: -10px;
        }
    }

    /* Ticker */

    .powertoys-footer-ticker {
        flex: 1;
        padding: 0 30px;
    }

    /* Create coupon */

    #quick-coupon-create .content div {
        display: flex;
    }

    @media (max-width: 1024px) {
        #jajuma-powertoys-floating-panel .power-toys-container {
            top: calc(100% + 5px);
            left: 5px !important;
            min-width: unset;
            max-width: unset;
            width: calc(100vw - 20px);
        }

        #jajuma-powertoys-floating-panel.powerToys-active.onRight .power-toys-container {
            transform: scale(1) translateX(calc(-100% + 50px));
        }

        #jajuma-powertoys-floating-panel.powerToys-active.onRight.onBottom .power-toys-container {
            top: -5px;
            left: 100% !important;
        }

        .powerToysModalWrapper .powertoys-modal {
            left: 10px !important;
            min-width: unset;
            max-width: unset;
            width: calc(100vw - 20px);
        }


        #jajuma-powertoys-floating-panel~.powerToysModalWrapper .powertoys-modal.open {
            transform: scale(1) translateX(0%);
        }

        .powertoys-footer-ticker {
            display: none;
        }
    }

    @keyframes widgetspinner {
        to {
            transform: rotate(360deg);
        }
    }

    .widget-item.widgetloading:before, .widget-action-button-div.widgetloading:before {
        content: '';
        box-sizing: border-box;
        position: absolute;
        top: 50%;
        left: 50%;
        width: 20px;
        height: 20px;
        margin-top: -10px;
        margin-left: -10px;
        border-radius: 50%;
        border: 2px solid #ccc;
        border-top-color: #000;
        animation: widgetspinner .6s linear infinite;
    }

    .widget-action-button-div.widgetloading {
        min-width: 5rem;
        min-height: 20px;
    }

    .powertoys-actions-list:not(.dragging),
    .powertoys-dashboard-widgets:not(.dragging),
    .powertoys-bookmark-bar:not(.dragging) {
        scroll-snap-type: x mandatory;
    }

    .powertoys-actions-list > li,
    .powertoys-dashboard-widgets > .widget-item,
    .powertoys-bookmark-bar > .bookmark-item{
        scroll-snap-align: start;
    }

    .powertoys-actions-list.dragging > li,
    .powertoys-dashboard-widgets.dragging > .widget-item,
    .powertoys-bookmark-bar.dragging > .bookmark-item{
        pointer-events: none;
    }

    .editmode iframe {
        pointer-events: none;
    }

    .pot-toggle {
        cursor: pointer;
        display: inline-block;
        margin-right: 1rem;
    }

    .pot-toggle-switch {
        display: inline-block;
        background: #ccc;
        border-radius: 16px;
        width: 40px;
        height: 20px;
        position: relative;
        vertical-align: middle;
        transition: background 0.25s;
    }

    .pot-toggle-switch:before,
    .pot-toggle-switch:after {
        content: "";
    }

    .pot-toggle-switch:before {
        display: block;
        background: linear-gradient(to bottom, #fff 0%, #eee 100%);
        border-radius: 50%;
        box-shadow: 0 0 0 1px rgba(0, 0, 0, 0.25);
        width: 16px;
        height: 16px;
        position: absolute;
        top: 2px;
        left: 2px;
        transition: left 0.25s;
    }

    .pot-toggle:hover .pot-toggle-switch:before {
        background: linear-gradient(to bottom, #fff 0%, #fff 100%);
        box-shadow: 0 0 0 1px rgba(0, 0, 0, 0.5);
    }

    .pot-toggle-checkbox:checked + .pot-toggle-switch {
        background: #ffe9a3;
    }

    .pot-toggle-checkbox:checked + .pot-toggle-switch:before {
        left: 22px;
    }

    .pot-toggle-checkbox {
        position: absolute;
        visibility: hidden;
    }

    .pot-toggle-label {
        margin-left: 5px;
        position: relative;
        top: 2px;
    }

    @media (max-width: 480px) {
        .pot-toggle {
            display: none;
        }
    }
</style>
